{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.6.2-SNAPSHOT.f55d4283",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.6.2-SNAPSHOT.f55d4283.aar",
          "url": "truemetricssdk-1.6.2-SNAPSHOT.f55d4283.aar",
          "size": 1671285,
          "sha512": "1c802101c74f977a24731cc2479f03f24a3a1d0e1b13c7b0f22eedcc61cfab940fe60ca50ea21413645ef0c45251fe2db3d3206998ca5eca61cf4dc9fe03860d",
          "sha256": "e0079207def26d44316affb80396a4ecc5539a25bc3336ed5f3001bda365e61f",
          "sha1": "fcb4b26510dde1625084c79f90d48ce05c353904",
          "md5": "b99c47dd1c58d1c44e99feca371fa429"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.6.2-SNAPSHOT.f55d4283.aar",
          "url": "truemetricssdk-1.6.2-SNAPSHOT.f55d4283.aar",
          "size": 1671285,
          "sha512": "1c802101c74f977a24731cc2479f03f24a3a1d0e1b13c7b0f22eedcc61cfab940fe60ca50ea21413645ef0c45251fe2db3d3206998ca5eca61cf4dc9fe03860d",
          "sha256": "e0079207def26d44316affb80396a4ecc5539a25bc3336ed5f3001bda365e61f",
          "sha1": "fcb4b26510dde1625084c79f90d48ce05c353904",
          "md5": "b99c47dd1c58d1c44e99feca371fa429"
        }
      ]
    }
  ]
}
