{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.5.8-SNAPSHOT.5d10b38c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.5.8-SNAPSHOT.5d10b38c.aar",
          "url": "truemetricssdk-1.5.8-SNAPSHOT.5d10b38c.aar",
          "size": 1595438,
          "sha512": "7bb62a6317340351d75c3056890c9f5cf50ffbfbaaab9eb1cd32225752d9bca509dadf5f5dd7020c160a837a2c6f2b67b081a9f7ca413420fb1cb92410b3a07f",
          "sha256": "dfe99fc0ed0129b0b017669e852d6a57b76194f4321737021c32de6448a1a19a",
          "sha1": "98a6854a3cc1d133c2f330df4bed83c02e1d45c3",
          "md5": "ea6363b54e4cec55038bce446a0016b9"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.5.8-SNAPSHOT.5d10b38c.aar",
          "url": "truemetricssdk-1.5.8-SNAPSHOT.5d10b38c.aar",
          "size": 1595438,
          "sha512": "7bb62a6317340351d75c3056890c9f5cf50ffbfbaaab9eb1cd32225752d9bca509dadf5f5dd7020c160a837a2c6f2b67b081a9f7ca413420fb1cb92410b3a07f",
          "sha256": "dfe99fc0ed0129b0b017669e852d6a57b76194f4321737021c32de6448a1a19a",
          "sha1": "98a6854a3cc1d133c2f330df4bed83c02e1d45c3",
          "md5": "ea6363b54e4cec55038bce446a0016b9"
        }
      ]
    }
  ]
}
