{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.6.aar",
          "url": "truemetricssdk-1.0.6.aar",
          "size": 565761,
          "sha512": "f7809d13b9439c19d8223ac28d802355fd12332418c9e14c000083bf9378990621af6c6a0bf979f343b6907f5e76798e4dd54745eee8d3426fc7fab9e445de8d",
          "sha256": "0fbc44f6989a67e9b82ab745491a52478f74bf3107ef0ac26fba84a49b21a90b",
          "sha1": "9e8aed55008cd2ad82c8b36ec84394fb21f2bc0e",
          "md5": "6892d651196865b296a2ed56ac9886ea"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.30.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.6.aar",
          "url": "truemetricssdk-1.0.6.aar",
          "size": 565761,
          "sha512": "f7809d13b9439c19d8223ac28d802355fd12332418c9e14c000083bf9378990621af6c6a0bf979f343b6907f5e76798e4dd54745eee8d3426fc7fab9e445de8d",
          "sha256": "0fbc44f6989a67e9b82ab745491a52478f74bf3107ef0ac26fba84a49b21a90b",
          "sha1": "9e8aed55008cd2ad82c8b36ec84394fb21f2bc0e",
          "md5": "6892d651196865b296a2ed56ac9886ea"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.6-sources.jar",
          "url": "truemetricssdk-1.0.6-sources.jar",
          "size": 147247,
          "sha512": "74b9553c1a4abb6d7fa12933ccf5daadb10c5131574908110e335ef504211443e47dfdd006f2b407fadfb8f363d5101fa0f8c02b1f6e05d74da676ae70b524ae",
          "sha256": "d50fefde0f72fb9fb199e91835ed7e3ebee4ec81e29e786076f4ad1ea026c1bf",
          "sha1": "3d29f8f75ee217280517c53f5eb72ca15b23337e",
          "md5": "26f56b23cf2e06ca26cf31c5f436f543"
        }
      ]
    }
  ]
}
