{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "de.jensklingenberg.ktorfit",
          "module": "ktorfit-lib",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.5.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sqlcipher-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.2.0.aar",
          "url": "truemetricssdk-1.2.0.aar",
          "size": 640497,
          "sha512": "ece46601da8f4934c9232a43ff3754834c62e9d0da45eac64712152200273bfdeac62cb215b473a855368744b30bf24767cf7963c34d78bcf07bcd14089718eb",
          "sha256": "00b52b6abc9e68e7bb1e1c5c28307ad6feabb36d8eaa1bece16dbaf69214670b",
          "sha1": "c3fb948c47256b1e178e21d7b28473e469b43ae8",
          "md5": "4ec68db2cfb9a4aebe36817d0c62152e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "de.jensklingenberg.ktorfit",
          "module": "ktorfit-lib",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.5.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sqlcipher-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.2.0.aar",
          "url": "truemetricssdk-1.2.0.aar",
          "size": 640497,
          "sha512": "ece46601da8f4934c9232a43ff3754834c62e9d0da45eac64712152200273bfdeac62cb215b473a855368744b30bf24767cf7963c34d78bcf07bcd14089718eb",
          "sha256": "00b52b6abc9e68e7bb1e1c5c28307ad6feabb36d8eaa1bece16dbaf69214670b",
          "sha1": "c3fb948c47256b1e178e21d7b28473e469b43ae8",
          "md5": "4ec68db2cfb9a4aebe36817d0c62152e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.2.0-sources.jar",
          "url": "truemetricssdk-1.2.0-sources.jar",
          "size": 194929,
          "sha512": "ba2ace9edfed2a3d2bc76b1ac1c44c38a5d6893244d94352823cd98b1214e42fcea73cb8b52cfd2d3f71dde2f8a382004aa32f547ee753ca2b65ba9d285b3c08",
          "sha256": "9f6d30b6b1e822b5a773246335b1ee965a55da87f90dc70000327ecb93d01185",
          "sha1": "ef8a196f8d88296406c4f56841c286849fc5326b",
          "md5": "0284adb6d9b944b3bde19be1fe253780"
        }
      ]
    }
  ]
}
