{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.17.aar",
          "url": "truemetricssdk-1.0.17.aar",
          "size": 616426,
          "sha512": "6d397e1f4426a2a70936f202dba9f1629c7ba3d646ec19f8b12c68ec00d73a1f4353fd8c502e5431a142a34be9739cf0f026af63ad4373f32c120649c8298158",
          "sha256": "40677dc1d3e1d3d59751dbe459421cb10f2baadddbc5de1a199457bc4c4b1478",
          "sha1": "b8bdd7e3b923304100ff6dcf85fa79a85105abf0",
          "md5": "27361150c04f14dd1b730c6fc0894cf3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.30.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.17.aar",
          "url": "truemetricssdk-1.0.17.aar",
          "size": 616426,
          "sha512": "6d397e1f4426a2a70936f202dba9f1629c7ba3d646ec19f8b12c68ec00d73a1f4353fd8c502e5431a142a34be9739cf0f026af63ad4373f32c120649c8298158",
          "sha256": "40677dc1d3e1d3d59751dbe459421cb10f2baadddbc5de1a199457bc4c4b1478",
          "sha1": "b8bdd7e3b923304100ff6dcf85fa79a85105abf0",
          "md5": "27361150c04f14dd1b730c6fc0894cf3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.17-sources.jar",
          "url": "truemetricssdk-1.0.17-sources.jar",
          "size": 162691,
          "sha512": "53847a9a1973924d78f9ebe8d3285cdbd10ee4f4fc0cf1488a735b20dbae11f4f79355a3208a69ef4ce6f4e61f3f05f931ec0c859ec1b4517dd79abbe3e54436",
          "sha256": "f620783dbbfe7c0ac9f40c1f9b935750e55e420aee7cc4df575653deeee1db7d",
          "sha1": "aa128a472be75d21a288ea89e30fd3c196c464a5",
          "md5": "cc00aca03afb8c68fbf1442d40cc1f19"
        }
      ]
    }
  ]
}
