{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.11.aar",
          "url": "truemetricssdk-1.0.11.aar",
          "size": 615934,
          "sha512": "65b2b147f5a7fc04534483ea29f3290c984323e11e5a45ff9213c920bc62728ac3c5cdaabdf855e22ec8a755255d5acbea4e9df22773b325778b0f61d514626d",
          "sha256": "626d63d4ba6b2d81b28e6f1982b7e74f0147573c89e8ae6a59a0725f5be7c689",
          "sha1": "bb6a96b9c2cf4016e9bd4d6a1cd2676812323d58",
          "md5": "a5954c3041de35c5229a78290fbacba8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.30.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.11.aar",
          "url": "truemetricssdk-1.0.11.aar",
          "size": 615934,
          "sha512": "65b2b147f5a7fc04534483ea29f3290c984323e11e5a45ff9213c920bc62728ac3c5cdaabdf855e22ec8a755255d5acbea4e9df22773b325778b0f61d514626d",
          "sha256": "626d63d4ba6b2d81b28e6f1982b7e74f0147573c89e8ae6a59a0725f5be7c689",
          "sha1": "bb6a96b9c2cf4016e9bd4d6a1cd2676812323d58",
          "md5": "a5954c3041de35c5229a78290fbacba8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.11-sources.jar",
          "url": "truemetricssdk-1.0.11-sources.jar",
          "size": 162491,
          "sha512": "b11337779dca9fe5f2549c91f1f871f50ec905632b3e170b21bc26133805b2e3ec6bc80ae8a6f26d220dfdd48cf363bb013a6ade59932c797034e1e641e14032",
          "sha256": "f26e61bac3a44dcb5e4599040c868793a29e6bef00a4ad0c9771f02529cf1c77",
          "sha1": "7144fedd8552652ab11c91f5a6950dd5d595d829",
          "md5": "047afc6e88b74bd5255e2d985ed2a9a3"
        }
      ]
    }
  ]
}
