{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.5.aar",
          "url": "truemetricssdk-1.0.5.aar",
          "size": 562089,
          "sha512": "a2626266a06e9e0608fdc7e179e975f679ad565ab5e4be814d85e8b5c65636299dde8b2d6d253c2c132864f968e005d53f887c38c24778bdec2b99cfa15128ba",
          "sha256": "b633a33be93623ef60602a0fcc3d72e8d1b3c2eee3b8ef6715aa4203da705a80",
          "sha1": "b2fedc2963eefc9740d8b9d48b4e0b21b316c96b",
          "md5": "6a24d91264257c80b0d595b1f81bbd12"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.30.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.5.aar",
          "url": "truemetricssdk-1.0.5.aar",
          "size": 562089,
          "sha512": "a2626266a06e9e0608fdc7e179e975f679ad565ab5e4be814d85e8b5c65636299dde8b2d6d253c2c132864f968e005d53f887c38c24778bdec2b99cfa15128ba",
          "sha256": "b633a33be93623ef60602a0fcc3d72e8d1b3c2eee3b8ef6715aa4203da705a80",
          "sha1": "b2fedc2963eefc9740d8b9d48b4e0b21b316c96b",
          "md5": "6a24d91264257c80b0d595b1f81bbd12"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.5-sources.jar",
          "url": "truemetricssdk-1.0.5-sources.jar",
          "size": 145939,
          "sha512": "eb9b70474037d2a0ac12e32bc108b714909facc3fca9efeeaad84380608e0793ac93d1cb5205fedb5abeb52495157320a4807497e76eb5c58d36fcf2e9d6ed45",
          "sha256": "68ee76a7d41b34353c81b29891996403832e8c4039fcc4a0c64ac7eb03484d6e",
          "sha1": "bcad86146087624a4773694b7f98846f63e9976d",
          "md5": "8a9a9f9cad938135b325611f5c860d9b"
        }
      ]
    }
  ]
}
