{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.7.aar",
          "url": "truemetricssdk-1.0.7.aar",
          "size": 567579,
          "sha512": "16ab55bd02a3bb9ceda5f753043bf40168337d1d3ee3a04878c4681d76ab2116cbd92dbb279ba00d472c36f8d1f2963d6e4e7e64b30452fb7b48cfb0aba4b34d",
          "sha256": "6757eb8e9c223505463a7d6fb23562376b4ac5598926e188bcc09bd7dc3c43f5",
          "sha1": "3206c02a344d1a4f36aae30cdc4f459ccccb116c",
          "md5": "2364e59b1587aa3c591ea336e15083a3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.30.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.7.aar",
          "url": "truemetricssdk-1.0.7.aar",
          "size": 567579,
          "sha512": "16ab55bd02a3bb9ceda5f753043bf40168337d1d3ee3a04878c4681d76ab2116cbd92dbb279ba00d472c36f8d1f2963d6e4e7e64b30452fb7b48cfb0aba4b34d",
          "sha256": "6757eb8e9c223505463a7d6fb23562376b4ac5598926e188bcc09bd7dc3c43f5",
          "sha1": "3206c02a344d1a4f36aae30cdc4f459ccccb116c",
          "md5": "2364e59b1587aa3c591ea336e15083a3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.7-sources.jar",
          "url": "truemetricssdk-1.0.7-sources.jar",
          "size": 147697,
          "sha512": "33ac4cd8545163ccee51191d2a72dc312996581314e4ba51f18625965f0709ebf0729a52c981f2620edcd27d60a231f19f0703d989920f02493660f07a35f01b",
          "sha256": "87f99e1a2d50cc3e80615b4c14e9e8a6f02426bbccdea476b06e5b50ec633d23",
          "sha1": "d646795f40179b40f3f01960fd7b8fa404e68684",
          "md5": "017462629fb7817a40f1f9cb172632d4"
        }
      ]
    }
  ]
}
