{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.14.aar",
          "url": "truemetricssdk-1.0.14.aar",
          "size": 621825,
          "sha512": "895406b50847251b0fd0e2b376e6297c9b50f22985d01720489bf6f23d83d010065551cd68abcf796529f958e23970016d4739731386d6090d351d5473802b06",
          "sha256": "bb8372f478624502703752096250ce3605f294dfb794964e878a74e04dfefb1f",
          "sha1": "a67adb651708fa8e0abf85d63ea4031c2a40d7c1",
          "md5": "8f9fc9e29b7214e5c04e25e727750c91"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.30.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.14.aar",
          "url": "truemetricssdk-1.0.14.aar",
          "size": 621825,
          "sha512": "895406b50847251b0fd0e2b376e6297c9b50f22985d01720489bf6f23d83d010065551cd68abcf796529f958e23970016d4739731386d6090d351d5473802b06",
          "sha256": "bb8372f478624502703752096250ce3605f294dfb794964e878a74e04dfefb1f",
          "sha1": "a67adb651708fa8e0abf85d63ea4031c2a40d7c1",
          "md5": "8f9fc9e29b7214e5c04e25e727750c91"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.14-sources.jar",
          "url": "truemetricssdk-1.0.14-sources.jar",
          "size": 163119,
          "sha512": "32c6dac1094154e840b2123a68d1ad785d85029789c0efc29d80a5ac3c208fba2a74abdbf45044548d02596e0dd99ff8f9b05558033a6fd0f3c0d3267c785ce1",
          "sha256": "ac7a539db04baf904f6c6a05405d26973a15a67d6937e945d0ab7dfac604e44f",
          "sha1": "cb005dce305618becfe7ec20ce68af9b509a801f",
          "md5": "9daf4cd58059ff1415ce42544e0e4e79"
        }
      ]
    }
  ]
}
