{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.2.aar",
          "url": "truemetricssdk-1.0.2.aar",
          "size": 485317,
          "sha512": "af390dc4d962e8ae22faf7c3a532424a4a1c1e6057c04a0c94426e55ea6ce3b454a7cde06350b97695ec740ade7fdf3d623b7dd583f5fc70bb0677b3efb57846",
          "sha256": "adff605a39bffdaf604e65a7a1098e89a6457f6703ad3c501d0bbd5ef73c1c3e",
          "sha1": "50ac7efc62c0dff5a6459a714e9b8dc54ccc2320",
          "md5": "da2e9969956a7e0acd0548186dcbc2bf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0-RC"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.2.aar",
          "url": "truemetricssdk-1.0.2.aar",
          "size": 485317,
          "sha512": "af390dc4d962e8ae22faf7c3a532424a4a1c1e6057c04a0c94426e55ea6ce3b454a7cde06350b97695ec740ade7fdf3d623b7dd583f5fc70bb0677b3efb57846",
          "sha256": "adff605a39bffdaf604e65a7a1098e89a6457f6703ad3c501d0bbd5ef73c1c3e",
          "sha1": "50ac7efc62c0dff5a6459a714e9b8dc54ccc2320",
          "md5": "da2e9969956a7e0acd0548186dcbc2bf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.2-sources.jar",
          "url": "truemetricssdk-1.0.2-sources.jar",
          "size": 127195,
          "sha512": "93e85db7cb12324e421f64efef494366a70424556275b9111d62d5aacd669ef30f55108a0ed4028f8f5422c48d2611defefd96df0efffe79e6d7d4160a19d401",
          "sha256": "78ab0acb41ce19b13843689d4793b66f386c4923be68083ae344ba3f886c156d",
          "sha1": "67b38c14217f4ad24572aa5384be8d6653544afd",
          "md5": "2e818300d80a3ea2f91c3256f4fe442d"
        }
      ]
    }
  ]
}
