{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.1.1.aar",
          "url": "truemetricssdk-1.1.1.aar",
          "size": 621637,
          "sha512": "49d6489d6c96a8b13c18e9071336c658451bb0f066aca0f9bc7cca6d87821f270bc2cb1f0cdf53cdea1ae45096cafd1b02c8a8a88923cbf4d4e12ecdb9969eac",
          "sha256": "fb43214204ca7410f0a278714448a3af3a7edd8150f6ded9308d3e84ffdbbd72",
          "sha1": "cfe68037942b7874f7c47897a09489b80806bea5",
          "md5": "f13292b78deb637fabcfb0d30cf416fc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.5.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sqlcipher-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.1.1.aar",
          "url": "truemetricssdk-1.1.1.aar",
          "size": 621637,
          "sha512": "49d6489d6c96a8b13c18e9071336c658451bb0f066aca0f9bc7cca6d87821f270bc2cb1f0cdf53cdea1ae45096cafd1b02c8a8a88923cbf4d4e12ecdb9969eac",
          "sha256": "fb43214204ca7410f0a278714448a3af3a7edd8150f6ded9308d3e84ffdbbd72",
          "sha1": "cfe68037942b7874f7c47897a09489b80806bea5",
          "md5": "f13292b78deb637fabcfb0d30cf416fc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.1.1-sources.jar",
          "url": "truemetricssdk-1.1.1-sources.jar",
          "size": 194125,
          "sha512": "6368d6c226119e710a7f9fe5ddd18deda6b07e10aa7854a6812099a2f31e16a9e6e6c6fa2ac4a644b9f81fa18bc5b3c624793c63182e954723a048815a13facb",
          "sha256": "f35793a6bcbbe2d76da3ab4db3714530de1c27ef28fba57f368dc055b9c06e1b",
          "sha1": "f47386f1e7b6d1f8091b593818e4e1f1e8a27a0b",
          "md5": "39cda7e5235c13c75e694a72baafc0f8"
        }
      ]
    }
  ]
}
