{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.13.aar",
          "url": "truemetricssdk-1.0.13.aar",
          "size": 621912,
          "sha512": "c0da90fa0079c94d47c481cc6516b6581a39db339c9a08d6b0c38cd08d214ec5a0883b2579cc87e80e7055070e2c4d5386383f990e40f7b06ef2be5d58d45d69",
          "sha256": "80c474c08605319cf4d0fa07d3401366cb1d7f8c03cebbc1fe604087f6833c3d",
          "sha1": "05ed959691d576f9de9f3fe8819cd8ddc15f662a",
          "md5": "ba22300f84df7f6aaad53cc4c2e32cc4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.30.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.13.aar",
          "url": "truemetricssdk-1.0.13.aar",
          "size": 621912,
          "sha512": "c0da90fa0079c94d47c481cc6516b6581a39db339c9a08d6b0c38cd08d214ec5a0883b2579cc87e80e7055070e2c4d5386383f990e40f7b06ef2be5d58d45d69",
          "sha256": "80c474c08605319cf4d0fa07d3401366cb1d7f8c03cebbc1fe604087f6833c3d",
          "sha1": "05ed959691d576f9de9f3fe8819cd8ddc15f662a",
          "md5": "ba22300f84df7f6aaad53cc4c2e32cc4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.13-sources.jar",
          "url": "truemetricssdk-1.0.13-sources.jar",
          "size": 163093,
          "sha512": "c775ac2278744e4503a687374b4258afaaa745367e5a76031d045b33d1e76f48d9a5aa980c98fca227f57998aaf9a83edbfd06bf67b2e612d894c376a6a3fb7d",
          "sha256": "9bdadbd78b643d9b46b99c3b5955488e22dbd9731b45c899ce4982b7b307b2b4",
          "sha1": "791e265cbc2927bfb6e008f076d06856ed3df8bf",
          "md5": "3e22bde2bb3944ec9a61c564544abafa"
        }
      ]
    }
  ]
}
