{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.9.aar",
          "url": "truemetricssdk-1.0.9.aar",
          "size": 569767,
          "sha512": "d2d88553a9c631bde451b6c13c3a5ecf7c8ffe725e53967f23e076da62b6ec5c3623c47e869e43d255504db833e4e11e9df2b38727392dc6c980bc7978955771",
          "sha256": "d24fbb4c3f0cceaefe774656e105563c7f99994aa461dce82b773856967e06fe",
          "sha1": "8f00ce6f625921fd6f8e8f4c8885395ec13344fe",
          "md5": "cb34d1797dd3522337be9db1208d673b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.30.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.0.9.aar",
          "url": "truemetricssdk-1.0.9.aar",
          "size": 569767,
          "sha512": "d2d88553a9c631bde451b6c13c3a5ecf7c8ffe725e53967f23e076da62b6ec5c3623c47e869e43d255504db833e4e11e9df2b38727392dc6c980bc7978955771",
          "sha256": "d24fbb4c3f0cceaefe774656e105563c7f99994aa461dce82b773856967e06fe",
          "sha1": "8f00ce6f625921fd6f8e8f4c8885395ec13344fe",
          "md5": "cb34d1797dd3522337be9db1208d673b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "truemetricssdk-1.0.9-sources.jar",
          "url": "truemetricssdk-1.0.9-sources.jar",
          "size": 148047,
          "sha512": "56a8dd1faf53b1bc476761c320fe244ccd6253830a6afe4b3255c91373e715b5f55ff66adeca8c96429266b1511d9f21718fd656a6c38a161c36d9f92f2ba32a",
          "sha256": "85a9c9191772e8c34b9b282b5235b33a3c12cb407569ab2c427a0d111c721490",
          "sha1": "2546565d6095cc208a1bb8bb88320d0de8f11472",
          "md5": "f9f956d57ef341850cf3d66190f4fccb"
        }
      ]
    }
  ]
}
