{
  "formatVersion": "1.1",
  "component": {
    "group": "io.truemetrics",
    "module": "truemetricssdk",
    "version": "1.6.1-SNAPSHOT.d375babf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.6.1-SNAPSHOT.d375babf.aar",
          "url": "truemetricssdk-1.6.1-SNAPSHOT.d375babf.aar",
          "size": 1648518,
          "sha512": "a4e83b5485028e264dc4558366f7d346b4d30d63ec7a1d8b8b004015b04e67289ec4751b7ae5086f67086769e4c27bc03ae00f8c7ef1768b7ae903238e2eb552",
          "sha256": "18052e5033ea76434e26d35d878445f825452444b9d1486276b06d0846887922",
          "sha1": "30e959d1964e1529a49cace824efb79c68a020b4",
          "md5": "ec89b457a65fbc961d078c95b95f57bd"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "truemetricssdk-1.6.1-SNAPSHOT.d375babf.aar",
          "url": "truemetricssdk-1.6.1-SNAPSHOT.d375babf.aar",
          "size": 1648518,
          "sha512": "a4e83b5485028e264dc4558366f7d346b4d30d63ec7a1d8b8b004015b04e67289ec4751b7ae5086f67086769e4c27bc03ae00f8c7ef1768b7ae903238e2eb552",
          "sha256": "18052e5033ea76434e26d35d878445f825452444b9d1486276b06d0846887922",
          "sha1": "30e959d1964e1529a49cace824efb79c68a020b4",
          "md5": "ec89b457a65fbc961d078c95b95f57bd"
        }
      ]
    }
  ]
}
